### ISSUE TITLE
ColorPicker Bug with HighFX LowFX macros creation

### ISSUE THREAD

**Issue by brutal1s** [FlorianANAYA/GrandMA2-help#2]
Hello Florian!
I recently found your plugin and I really like it. Thanks for your work.
But I have a problem. When I set the plugin in the line createColorFXSelector = false, they do not work. ColorFXSelector is still created. And I can't solve this problem. Maybe you can help me?

**Comment by FlorianANAYA** [comment]
Hello !
Thank you for bringing this up to me ! The bug is now fixed, I will now close this issue.
Let me know if you need anything else
